service: vivify-backend-express

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  profile: default

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      SPOTIFY_ID: ${ssm:spotify_id}
      SPOTIFY_SECRET: ${ssm:spotify_secret}
